<a href="https://colab.research.google.com/github/Alexandr-M-85/Neural-University/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy. Домашнее Задание. Ultra-Pro

### Задача 1
*(1 балл)*

Создайте единичную матрицу размером 5*5.

**Должна получиться матрица вида**

**1** 0 0 0 0 

0 **1** 0 0 0 

0 0 **1** 0 0 

0 0 0 **1** 0 

0 0 0 0 **1** 

**Действовать можно двумя путями:**

1. Используя соответствующий метод Numpy. (О нем не говорилось в занятии. Стоит обратиться к документации Numpy).
2. Если первый вариант сложный, можно создать массив из нулей, используя метод, о котором говорилось в занятии. В цикле заменить все элементы по диагонали на единицы. 






**Решение:**

In [ ]:
# импортируем библиотеку numpy
import numpy as np
# создадим единичную матрицу размером 5*5 с использованием специальной функции eye()
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

###Задача 2
*(2 балла)*

Создайте массив из случайных значений из стандартного нормального распределения размера 6 на 6. 

Разверните массив таким образом, чтобы его размер стал 36 на 1.
Найдите среднее значение элементов массива.

**Разрешается использовать только методы Numpy. (Циклы и условия запрещены)**.

**Решение:**

In [ ]:
# создадим массив из случайных значений из стандартного нормального распределения размера 6 на 6
norm_array = np.random.normal(0, 2, size=(6, 6))
print(norm_array)

[[-2.23471126  0.22269779  3.34049566 -0.42452507 -1.45460924  0.49608217]
 [-0.12732058  1.28014777  1.53387203  0.87695855  3.12781397  3.69581769]
 [ 1.83091726  2.31005764  0.87288818 -1.63348564 -2.7296584  -0.74363154]
 [-0.70233276  1.38654666  0.87519562 -3.63445675 -2.88238759  0.45465817]
 [-1.25208288  1.53108576  1.02530929 -3.56408008  0.44917117 -0.69075029]
 [-1.43756109  0.04550134  2.10358374 -3.95694844  0.37930637  1.56044875]]


In [ ]:
# изменим размер массива на размер 36 на 1
norm_array = norm_array.reshape(36, 1)
print(norm_array)

[[-2.23471126]
 [ 0.22269779]
 [ 3.34049566]
 [-0.42452507]
 [-1.45460924]
 [ 0.49608217]
 [-0.12732058]
 [ 1.28014777]
 [ 1.53387203]
 [ 0.87695855]
 [ 3.12781397]
 [ 3.69581769]
 [ 1.83091726]
 [ 2.31005764]
 [ 0.87288818]
 [-1.63348564]
 [-2.7296584 ]
 [-0.74363154]
 [-0.70233276]
 [ 1.38654666]
 [ 0.87519562]
 [-3.63445675]
 [-2.88238759]
 [ 0.45465817]
 [-1.25208288]
 [ 1.53108576]
 [ 1.02530929]
 [-3.56408008]
 [ 0.44917117]
 [-0.69075029]
 [-1.43756109]
 [ 0.04550134]
 [ 2.10358374]
 [-3.95694844]
 [ 0.37930637]
 [ 1.56044875]]


In [ ]:
# найдем среднее значение элементов массива
norm_array.mean()

0.053611498640422806

###Задача 3
*(2 балла)*

Создайте массив из 20 любых случайных значений, используя метод Numpy.
Найдите значения производных для созданного массива

**Решение:**

In [ ]:
# создадим массив из 20 любых значений
new_array = np.random.random(20)
# найдем матрицу производных при помощи функции numpy.diff()
diff_array = np.diff(new_array)
print(new_array)
print(diff_array)

[0.77662344 0.42622078 0.22444337 0.59345164 0.79854207 0.51794179
 0.43766187 0.87749163 0.26111125 0.39428674 0.14167947 0.15708142
 0.88788471 0.1236999  0.82726928 0.64515499 0.7987456  0.47818899
 0.63312782 0.64585292]
[-0.35040265 -0.20177741  0.36900827  0.20509044 -0.28060028 -0.08027992
  0.43982975 -0.61638038  0.13317549 -0.25260727  0.01540195  0.73080329
 -0.76418481  0.70356938 -0.18211429  0.1535906  -0.3205566   0.15493882
  0.0127251 ]


###Задача 4
*(2 балла)*

Дано выражение

Y = A * X * C

Создайте три случайных массива A, C, X. Размерности должны позволять выполнить матричное умножение согласно формуле. На выходе должен получиться массив Y с размерностью (5, 18). (Остальные размерности возьмите на свое усмотрение).

**Решение:**

In [ ]:
# создадим массив А, C, X
A = np.random.randint(0, 10, (5,8))
C = np.random.randint(0, 10, (8,12))
X = np.random.randint(0, 10, (12,18))
# перемножим матрицы
Y = A.dot(C).dot(X)
print(Y)
print(Y.shape)

[[ 7048  7065  7715  8907  6291  5625  7367  8623  8485  7776  6273  9877
   7042  5345  7411  7607 10118  4438]
 [ 6710  6561  6978  7911  5716  5178  6343  7607  7816  7066  5238  9065
   6931  4911  6740  6741  9326  4251]
 [ 9592  9602 10341 11719  8662  7827  9704 10841 11669 10007  7678 13328
   9683  6990 10256  9850 13491  6460]
 [ 4543  4932  5412  6341  4826  4119  5446  5782  6081  5016  4084  7105
   5042  4192  5201  5204  6944  2901]
 [ 5905  5609  5835  6396  4821  4189  5555  6378  6434  6101  4635  7530
   5467  4155  5600  5944  7750  3404]]
(5, 18)


###Задача 5
*(3 балла)*

Загрузите какой-либо файл с данными (таблица Excel с Вашего компьютера, сохраненная в формате csv, или таблица из Интернета). Выведите следующее:

1. Всю информацию из файла в ячейку. 
2. Размерность данных. 
3. Среднее арифметическое от всех числовых значений (если есть).
4. Число столбов. 
5. Число строк.
6. Типы данных всех значений. 

**Решение:**

In [ ]:
# загрузим файл с данными в переменную my_data
np.set_printoptions(threshold=5000)
my_data = np.loadtxt('/content/admission.csv', delimiter=',', skiprows=1)
print(my_data)

[[1.00e+00 3.37e+02 1.18e+02 4.00e+00 4.50e+00 4.50e+00 9.65e+00 1.00e+00
  9.20e-01]
 [2.00e+00 3.24e+02 1.07e+02 4.00e+00 4.00e+00 4.50e+00 8.87e+00 1.00e+00
  7.60e-01]
 [3.00e+00 3.16e+02 1.04e+02 3.00e+00 3.00e+00 3.50e+00 8.00e+00 1.00e+00
  7.20e-01]
 [4.00e+00 3.22e+02 1.10e+02 3.00e+00 3.50e+00 2.50e+00 8.67e+00 1.00e+00
  8.00e-01]
 [5.00e+00 3.14e+02 1.03e+02 2.00e+00 2.00e+00 3.00e+00 8.21e+00 0.00e+00
  6.50e-01]
 [6.00e+00 3.30e+02 1.15e+02 5.00e+00 4.50e+00 3.00e+00 9.34e+00 1.00e+00
  9.00e-01]
 [7.00e+00 3.21e+02 1.09e+02 3.00e+00 3.00e+00 4.00e+00 8.20e+00 1.00e+00
  7.50e-01]
 [8.00e+00 3.08e+02 1.01e+02 2.00e+00 3.00e+00 4.00e+00 7.90e+00 0.00e+00
  6.80e-01]
 [9.00e+00 3.02e+02 1.02e+02 1.00e+00 2.00e+00 1.50e+00 8.00e+00 0.00e+00
  5.00e-01]
 [1.00e+01 3.23e+02 1.08e+02 3.00e+00 3.50e+00 3.00e+00 8.60e+00 0.00e+00
  4.50e-01]
 [1.10e+01 3.25e+02 1.06e+02 3.00e+00 3.50e+00 4.00e+00 8.40e+00 1.00e+00
  5.20e-01]
 [1.20e+01 3.27e+02 1.11e+02 4.00e+00 4.00e+00 4.50e+0

In [ ]:
# размерность данных
print(my_data.shape)

(500, 9)


In [ ]:
# среднее арифметическое от всех числовых значений
print(my_data.mean())

77.11046444444443


In [ ]:
# кол-во столбцов
print(len(my_data[0]))

9


In [ ]:
# кол-во строк
print(len(my_data))

500


In [ ]:
# типы данных всех значений
print(my_data.dtype)

float64
